[[pages]]
path = "example_one.py"
name = "st-pages"
icon = "📄"

[[pages]]
name = "Cool apps"
icon = ":pig:"
is_section = true

[[pages]]
path = "example_four.py"
name = "Example Four"
icon = "📖"

[[pages]]
path = "example_two.py"
name = "Example Two"
icon = ":material/history:"

[[pages]]
name = "Other apps"
icon = ":horse:"
is_section = true

[[pages]]
path = "example_three.py"

[[pages]]
path = "example_five.py"
name = "Example Five"
icon = "🧰"
in_section = false
